FROM ubuntu:20.04

RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install -y python3
RUN apt-get install -y python3-pip
RUN apt-get install -y git

RUN git clone --depth 1 https://github.com/gomax22/Federated-FaceBoxes.git && cd Federated-FaceBoxes
WORKDIR /Federated-FaceBoxes
RUN python3 -m pip install --no-cache-dir -r requirements.txt

# ENTRYPOINT ["flower-server-app", "server:app"]
ENTRYPOINT ["python3", "server.py"]