FROM ubuntu:20.04

RUN apt-get update -y
RUN apt-get upgrade -y
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get install -y python3
RUN apt-get install -y python3-pip
RUN apt-get install -y git
RUN apt-get install -y python3-opencv


WORKDIR /app
COPY . .
RUN python3 -m pip install --no-cache-dir -r requirements.txt

# ENTRYPOINT ["flower-server-app", "server:app"]
ENTRYPOINT ["python3", "server.py"]